FROM node:20.19.0

# Instalar Angular CLI 21
RUN npm install -g @angular/cli@21

# Crear directorio de trabajo
WORKDIR /app

# Exponer el puerto de Angular
EXPOSE 4200

# Comando por defecto
CMD ["bash"]